### ISSUE TITLE
A New Issue for css

### ISSUE THREAD

**Issue by sriudemy** [srinath1/docker-react#1]
Made cghanges to css.
```css
.App {
  text-align: center;
  font-size: small;
}

.App-logo {
  height: 80vmin;
  pointer-events: none;
}



```
